# Retrieves a specific document

@organization_id=6fb292aa-ee38-48ae-998f-079ad9d01e7c
@document_id=http://localhost:8080/api/v1/documents/4a63c118-47f2-4358-a0b9-4562314663b4



GET http://{{$dotenv TRUSTED_PARTY_HOST}}:{{$dotenv TRUSTED_PARTY_PORT}}/api/v1/organizations/{{organization_id}}/documents/{{document_id}}/json HTTP/1.1
Accept: application/json
