spring:
  application:
    name: cpf-store
  neo4j:
    uri: ${NEO4J_URI:bolt://localhost:7687}
    authentication:
      username: ${NEO4J_USERNAME:neo4j}
      password: ${NEO4J_PASSWORD:s6cr9t}

trusted-party:
  url: ${TRUSTED_PARTY_URL:http://trustedparty:8080/api/v1/}

store:
  url: ${STORE_URL:http://localhost:8080/api/v1/}
  mode:
    verbose: ${CPF_STORE_VERBOSE_MODE:false}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

access:
  slow-request-warning-enabled: false
  slow-request-threshold-ms: 1000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    org.commonprovenance: INFO
