replicaCount: 1

image:
  repository: cerit.io/commonprovenanceframework/cpf-storage
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""
  annotations: {}

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  annotations: {}

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

springProfilesActive: prod

config:
  NEO4J_URI: bolt://neo4j:7687
  STORE_URL: http://localhost:8080/api/v1/
  TRUSTED_PARTY_URL: http://nro-service:8020/api/v1/
  CPF_STORE_VERBOSE_MODE: "false"

existingSecret:
  name: neo4j
  keys:
    NEO4J_USERNAME: neo4j-username
    NEO4J_PASSWORD: neo4j-password

extraEnv: []

startupProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  periodSeconds: 5
  failureThreshold: 30
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 6
livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 6
