package org.commonprovenance.framework.store.persistence.finalizedProvComponent.model.relation;

import org.commonprovenance.framework.store.persistence.finalizedProvComponent.model.node.TokenNode;
import org.springframework.data.annotation.PersistenceCreator;
import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.RelationshipProperties;
import org.springframework.data.neo4j.core.schema.TargetNode;

@RelationshipProperties
public final class HasToken {

  @Id
  @GeneratedValue
  private final String id;

  @TargetNode
  private final TokenNode token;

  // Constructor for full initialization (used by Neo4j when reading)
  @PersistenceCreator
  public HasToken(String id, TokenNode token) {
    this.id = id;
    this.token = token;
  }

  // Constructor for creating new relationships (id will be generated)
  public HasToken(TokenNode token) {
    this.id = null; // id will be generated by Neo4j
    this.token = token;
  }

  // Wither methods for immutability
  public HasToken withId(String id) {
    return new HasToken(id, this.getToken());
  }

  public HasToken withToken(TokenNode token) {
    return new HasToken(this.getId(), token);
  }

  // Getters

  public String getId() {
    return this.id;
  }

  public TokenNode getToken() {
    return this.token;
  }
}
